version: '3'
services:
  db:
    image: mysql
    platform: linux/x86_64
    build:
      context: ./db
      dockerfile: mysql-dockerfile
    volumes:
      - ./db/data:/var/lib/db/data
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Seoul'
    ports:
      - "3308:3306"

  gpt-redis:
    container_name: gpt-redis
    image: redis
    ports:
      - "6579:6379"